### PR TITLE
Added functionality to allow for looking up an IP address

### PR DESCRIPTION
**Pull request by mitchellkellett**
Addresses issue #20.

Added functionality to allow for looking up an IP address by using NGINX maps.
	- New map.conf that containing maps.
	- Updated nginx.conf to increase map_hash_bucket_size above default value.
	- Updated geoip2.conf to include new variables for lookup IP addresses.
	- Updated ipinfo.conf to include new location blocks to allow for looking up IP addresses.
Moved existing functionality for looking up requesting IP address to use NGINX maps.
	- Updated ipinfo.conf to remove old location blocks that have been moved to map.conf.
Updated README to include details on added functionality.

### CODE REVIEW

**Review by PeterDaveHello — COMMENTED** [review]
Thanks, as the change is huge, I'll take more time to take a look at it.

**Comment by mitchellkellett** [comment]
I've just found some bugs in it. I'm working to fix them. It's mostly the regex that I thought I had right.

**Comment by mitchellkellett** [comment]
Should be fixed now.

**Review by PeterDaveHello — CHANGES_REQUESTED** [review]
@mitchellkellett thanks for your help. I noticed that you also added/changed the function to show more details info like city. Can we separate that part in another pull request, and focus on the functionality to allow looking up a certain IP address? Thanks.

**Comment by PeterDaveHello** [comment]
Hi @mitchellkellett, would you like to continue this pull request ;)

**Comment by mitchellkellett** [comment]
> Hi @mitchellkellett, would you like to continue this pull request ;)

Sorry, I'll update this PR, just haven't had a chance to get to it yet.

**Comment by PeterDaveHello** [comment]
Thank you very much, looking forward to have your PR then 👍

**Pull request closed without merging**
